import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "../styles/globals.css"
import Header from "@/components/Header";
import { Container, ThemeProvider } from "@mui/material";
import theme from '../styles/theme'; 
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
     {/* <title>{metadata.title}</title>
      <meta name="description" content={metadata.description} /> */}
    </head>
    <body className={inter.className}>
    <ThemeProvider theme={theme}>
      <Header/>
        <div  className="child-container">
          {children}
        </div>
      <Footer />
    </ThemeProvider>
    </body>
  </html>
  );
}

const styles = {
  minHeight: {
      minHeight:'105vh'
  }
}